spring:
  thymeleaf:
    # 避免缓存HTML页面
    cache: false

  datasource:
    driver-class-name: org.h2.Driver
    password: "123"
    # 数据库连接 URL, 为了兼容MySQL, 添加 ;MODE=MySQL
    # ;DATABASE_TO_LOWER=TRUE 是让表名转为小写
    # ;CASE_INSENSITIVE_IDENTIFIERS=TRUE 不区分大小写
    # ;DB_CLOSE_DELAY=-1 不自动关闭数据库连接
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    username: sa

  h2:
    console:
      # 显示 H2嵌入式 UI管理界面
      enabled: true
      path: /h2-console
      settings:
        # 禁止输出Trace信息
        trace: false
        # 禁止远程访问H2管理界面
        web-allow-others: false

logging:
  level:
    com.billwen: DEBUG
    org.springframework.jdbc.core: TRACE
