logging:
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'

  level:
    org.springframework.security: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  server:
    port: 8081


server:
  port: 8080

spring:
  application:
    name: uaa

  security:
    user:
      name: user
      password: 12345678
      roles: USER,ADMIN

  messages:
    basename: message
    encoding: UTF-8


mooc:
  jwt:
    access-token-expire-time: 300000
    refresh-token-expire-time: 2592000000
  ali:
    api-key: ${ALI_API_KEY}
    api-secret: ${ALI_API_SECRET}

  sms-provider:
    name: ali
    apiUrl: www.aliyun.com