### GET Test
GET http://localhost:8080/api/greeting HTTP/1.1
Authorization: Basic user f56737e5-7dbf-44f9-8d4b-5266fa6197eb
Accept: application/json

### POST Test
POST http://localhost:8080/api/greeting?name=billwen
Authorization: Basic user f3e22166-da9b-4af3-8342-7b244c01d5e3

### PUT Test
PUT http://localhost:8080/api/greeting/gang.wen
Authorization: Basic user 1da5f891-0bc3-4c41-84df-005918080949

### Json payload
POST http://localhost:8080/api/jsonpayload
Authorization: Basic user 54384eef-ca6f-434f-b210-4c2d0151ccf0
Content-Type: application/json

{
"name": "superman"
}